-- =====================================================
-- Data Dictionary Update
-- Related Change ID: Change 018
-- Description: Refine species tables
-- =====================================================


-- 1. Update species.speciesid to reflect auto-generated identity */

UPDATE grp.data_dictionary
SET
    definition = 'Auto-generated primary key for each species or taxon record.',
    workflow_notes = 'Generated by PostgreSQL as an identity column. Do not manually populate during imports.',
    qa_qc_notes = 'Used as the primary key for species records and as the foreign key target for species-related join tables.'
WHERE table_name = 'species'
  AND column_name = 'speciesid';


-- 2. Rename data_dictionary entry from species_lifespan.description to species_lifespan.type */

UPDATE grp.data_dictionary
SET
    column_name = 'type',
    definition = 'Lifespan category assigned to a species.',
    workflow_notes = 'Must match an existing value in grp.lifespan.type.',
    allowed_values = 'annual; biennial; perennial',
    example = 'perennial',
    qa_qc_notes = 'Foreign key constrained to grp.lifespan(type). A species may have more than one lifespan type through this join table.'
WHERE table_name = 'species_lifespan'
  AND column_name = 'description';