-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 1: Separate import batches from import projects
-- =====================================================

ALTER TABLE grp.project
ADD CONSTRAINT project_database_projectid_unique
UNIQUE (database, projectid);

CREATE TABLE IF NOT EXISTS grp.import_project (
    import_projectid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    source_folder text,

    contribution_type text,

    contribution_period text,

    documentation_tier text,

    import_status text DEFAULT 'planned',

    import_started_at timestamp without time zone,

    import_completed_at timestamp without time zone,

    supersedes_import_projectid integer
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    is_current_version boolean DEFAULT true,

    notes text,

    CONSTRAINT import_project_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_project_contribution_type_check
        CHECK (contribution_type IN (
            'initial_import',
            'additional_contribution',
            'correction',
            'reprocessing',
            'test_import'
        )),

    CONSTRAINT import_project_documentation_tier_check
        CHECK (
            documentation_tier IS NULL
            OR documentation_tier IN (
                'legacy_minimal',
                'legacy_documented',
                'transformation_documented',
                'fully_reproducible'
            )
        ),

    CONSTRAINT import_project_status_check
        CHECK (import_status IN (
            'planned',
            'staged',
            'validated',
            'imported',
            'failed',
            'skipped'
        ))
);

COMMENT ON TABLE grp.import_project IS
'Tracks one project contribution/import event within an import batch. Allows repeated future contributions for the same project.';

CREATE INDEX IF NOT EXISTS idx_import_project_import_batchid
ON grp.import_project(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_project_projectid
ON grp.import_project(projectid);

CREATE INDEX IF NOT EXISTS idx_import_project_database_projectid
ON grp.import_project(database, projectid);
 
-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 2: Add artifact tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_artifact (
    import_artifactid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_projectid integer NOT NULL
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    artifact_type text NOT NULL,

    artifact_subtype text,

    file_name text,

    file_extension text,

    file_path_or_storage_key text,

    storage_bucket text,

    file_hash text,

    source_layer text,

    workflow_stage text,

    created_by text,

    created_date date,

    loaded_at timestamp without time zone,

    notes text,

    CONSTRAINT import_artifact_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_artifact_type_check
        CHECK (artifact_type IN (
            'raw_data',
            'harmonized_data',
            'transformation_code',
            'mapping_table',
            'transformation_table',
            'processed_output',
            'metadata',
            'notes',
            'other'
        ))
);

COMMENT ON TABLE grp.import_artifact IS
'Catalogues files and other provenance artifacts associated with project imports, including raw data, harmonized data, code, mapping tables, transformation tables, outputs, metadata, and documentation.';

CREATE INDEX IF NOT EXISTS idx_import_artifact_import_projectid
ON grp.import_artifact(import_projectid);

CREATE INDEX IF NOT EXISTS idx_import_artifact_import_batchid
ON grp.import_artifact(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_artifact_project
ON grp.import_artifact(database, projectid);

CREATE INDEX IF NOT EXISTS idx_import_artifact_type
ON grp.import_artifact(artifact_type);
 
-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 3: Add transformation tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_transformation_step (
    import_transformation_stepid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_projectid integer NOT NULL
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    step_order integer NOT NULL,

    step_name text NOT NULL,

    step_description text,

    transformation_type text,

    software_or_language text,

    notes text,

    CONSTRAINT import_transformation_step_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_transformation_step_order_check
        CHECK (step_order > 0)
);

COMMENT ON TABLE grp.import_transformation_step IS
'Documents ordered transformation steps showing how raw or contributed data become harmonized/import-ready data.';

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_import_projectid
ON grp.import_transformation_step(import_projectid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_import_batchid
ON grp.import_transformation_step(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_project
ON grp.import_transformation_step(database, projectid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_order
ON grp.import_transformation_step(import_projectid, step_order);


CREATE TABLE IF NOT EXISTS grp.import_transformation_step_artifact (
    import_transformation_step_artifactid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_transformation_stepid integer NOT NULL
        REFERENCES grp.import_transformation_step(import_transformation_stepid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_artifactid integer NOT NULL
        REFERENCES grp.import_artifact(import_artifactid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    artifact_role text NOT NULL,

    notes text,

    CONSTRAINT import_transformation_step_artifact_role_check
        CHECK (artifact_role IN (
            'input',
            'output',
            'code',
            'lookup',
            'mapping',
            'documentation',
            'other'
        ))
);

COMMENT ON TABLE grp.import_transformation_step_artifact IS
'Links artifacts to transformation steps as inputs, outputs, code, mappings, lookups, or documentation.';

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_artifact_stepid
ON grp.import_transformation_step_artifact(import_transformation_stepid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_artifact_artifactid
ON grp.import_transformation_step_artifact(import_artifactid);
 
-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 4: Add project object crosswalks
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.project_object_crosswalk (
    project_object_crosswalkid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    database text NOT NULL,

    projectid integer NOT NULL,

    import_projectid integer
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    object_type text NOT NULL,

    contributor_object_code text NOT NULL,
    contributor_object_label text,
    contributor_object_description text,

    grp_object_type text NOT NULL,
    grp_object_id integer,
    grp_object_code text,

    valid_from date,
    valid_to date,
    is_current boolean DEFAULT true,

    created_at timestamp without time zone DEFAULT now(),
    notes text,

    CONSTRAINT project_object_crosswalk_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT project_object_crosswalk_object_type_check
        CHECK (object_type IN (
            'project',
            'site',
            'area',
            'plot',
            'subplot',
            'treatment',
            'species',
            'sample',
            'observation',
            'other'
        )),

    CONSTRAINT project_object_crosswalk_current_date_check
        CHECK (
            valid_to IS NULL
            OR valid_from IS NULL
            OR valid_to >= valid_from
        )
);

COMMENT ON TABLE grp.project_object_crosswalk IS
'Stores reusable contributor-to-GRP object mappings for future imports, such as contributor plot codes mapped to GRP area or plot identifiers.';

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_project
ON grp.project_object_crosswalk(database, projectid);

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_import_projectid
ON grp.project_object_crosswalk(import_projectid);

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_lookup
ON grp.project_object_crosswalk(database, projectid, object_type, contributor_object_code);

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_current
ON grp.project_object_crosswalk(database, projectid, object_type, is_current);
 
-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 5: Add import validation issue tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_validation_issue (
    import_validation_issueid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_projectid integer
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    import_artifactid integer
        REFERENCES grp.import_artifact(import_artifactid)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    source_file text,
    source_sheet text,
    source_row_number integer,
    source_column text,

    target_table text,
    target_column text,

    issue_type text NOT NULL,
    issue_severity text NOT NULL DEFAULT 'warning',

    raw_value text,
    suggested_resolution text,

    resolved boolean DEFAULT false,
    resolved_at timestamp without time zone,
    resolution_notes text,

    notes text,

    CONSTRAINT import_validation_issue_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_validation_issue_severity_check
        CHECK (issue_severity IN (
            'info',
            'warning',
            'error',
            'blocker'
        )),

    CONSTRAINT import_validation_issue_type_check
        CHECK (issue_type IN (
            'missing_required_value',
            'lookup_mismatch',
            'species_code_not_found',
            'duplicate_key',
            'date_parse_error',
            'schema_gap',
            'unmapped_object',
            'unexpected_value',
            'data_type_mismatch',
            'referential_integrity_issue',
            'other'
        ))
);

COMMENT ON TABLE grp.import_validation_issue IS
'Tracks import warnings, errors, blockers, schema gaps, unmapped objects, and other issues discovered during staging, validation, or import.';

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_import_batchid
ON grp.import_validation_issue(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_import_projectid
ON grp.import_validation_issue(import_projectid);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_project
ON grp.import_validation_issue(database, projectid);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_severity
ON grp.import_validation_issue(issue_severity);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_resolved
ON grp.import_validation_issue(resolved);


-- =====================================================
-- Remove replaced import object mapping table
-- =====================================================

DROP TABLE IF EXISTS grp.import_object_map;