-- =====================================================
-- Species Table Refinement
-- Change 018: Species table refinement
-- Date: 2026-06-05
-- Purpose: Make ID auto-generated and refine lifespan type reference
-- =====================================================

-- Redefine grp.species.speciesid as auto-generated

ALTER TABLE grp.species
ALTER COLUMN speciesid
ADD GENERATED BY DEFAULT AS IDENTITY;

-- Rename grp.species_lifespan.description to type

ALTER TABLE grp.species_lifespan
RENAME COLUMN description TO type;

ALTER TABLE grp.species_lifespan
DROP CONSTRAINT "FK_Species_Lifespan.Description";

-- Rename grp.species_lifespan constraint accordingly

ALTER TABLE grp.species_lifespan
ADD CONSTRAINT "FK_Species_Lifespan.Type"
FOREIGN KEY (type)
REFERENCES grp.lifespan(type);