-- =====================================================
-- Dependency Checks
-- Related Change ID: Change 020
-- Description: Remove identity generation from
--              grp.paper.paperid
-- =====================================================

-- -----------------------------------------------------
-- 1. Confirm grp.paper and paperid exist
-- -----------------------------------------------------

SELECT
    table_schema,
    table_name,
    column_name,
    data_type,
    is_nullable,
    column_default,
    is_identity,
    identity_generation
FROM information_schema.columns
WHERE table_schema = 'grp'
  AND table_name = 'paper'
  AND column_name = 'paperid';

-- Expected before the change:
-- data_type: integer
-- is_nullable: NO
-- is_identity: YES
-- identity_generation: ALWAYS


-- -----------------------------------------------------
-- 2. Confirm the exact identity definition
-- -----------------------------------------------------

SELECT
    att.attname AS column_name,
    att.attidentity AS identity_code,
    CASE att.attidentity
        WHEN 'a' THEN 'GENERATED ALWAYS'
        WHEN 'd' THEN 'GENERATED BY DEFAULT'
        ELSE 'NOT IDENTITY'
    END AS identity_definition
FROM pg_attribute att
WHERE att.attrelid = 'grp.paper'::regclass
  AND att.attname = 'paperid'
  AND NOT att.attisdropped;

-- Expected before the change:
-- identity_code: a
-- identity_definition: GENERATED ALWAYS


-- -----------------------------------------------------
-- 3. Inspect the identity sequence
-- -----------------------------------------------------

SELECT
    pg_get_serial_sequence(
        'grp.paper',
        'paperid'
    ) AS paperid_identity_sequence;

-- Expected before the change:
-- grp.paper_paperid_seq


-- -----------------------------------------------------
-- 4. Confirm paperid remains suitable as a manually
--    populated primary key
-- -----------------------------------------------------

SELECT
    COUNT(*) AS total_papers,
    COUNT(paperid) AS populated_paperids,
    COUNT(DISTINCT paperid) AS distinct_paperids,
    MIN(paperid) AS minimum_paperid,
    MAX(paperid) AS maximum_paperid,
    CASE
        WHEN COUNT(*) = COUNT(paperid)
         AND COUNT(paperid) = COUNT(DISTINCT paperid)
        THEN 'PASS'
        ELSE 'FAIL'
    END AS result
FROM grp.paper;

-- Expected: PASS.


-- -----------------------------------------------------
-- 5. Confirm the paper primary key
-- -----------------------------------------------------

SELECT
    con.conname AS constraint_name,
    con.contype AS constraint_type,
    con.convalidated AS is_validated,
    pg_get_constraintdef(con.oid) AS constraint_definition
FROM pg_constraint con
WHERE con.conrelid = 'grp.paper'::regclass
  AND con.contype = 'p';

-- Expected:
-- paper_pkey PRIMARY KEY (paperid)


-- -----------------------------------------------------
-- 6. Inspect foreign keys that reference grp.paper
-- -----------------------------------------------------

SELECT
    con.conrelid::regclass AS referencing_table,
    con.conname AS constraint_name,
    con.convalidated AS is_validated,
    pg_get_constraintdef(con.oid) AS constraint_definition
FROM pg_constraint con
WHERE con.contype = 'f'
  AND con.confrelid = 'grp.paper'::regclass
ORDER BY con.conrelid::regclass::text, con.conname;

-- Expected to include foreign keys from:
-- grp.paper_author
-- grp.project_paper


-- -----------------------------------------------------
-- 7. Confirm existing referencing records are valid
-- -----------------------------------------------------

SELECT
    'paper_author' AS referencing_table,
    COUNT(*) AS orphaned_rows
FROM grp.paper_author pa
LEFT JOIN grp.paper p
  ON p.paperid = pa.paperid
WHERE p.paperid IS NULL

UNION ALL

SELECT
    'project_paper',
    COUNT(*)
FROM grp.project_paper pp
LEFT JOIN grp.paper p
  ON p.paperid = pp.paperid
WHERE p.paperid IS NULL;

-- Expected: zero orphaned rows for both tables.


-- -----------------------------------------------------
-- 8. Inspect paperid documentation
-- -----------------------------------------------------

SELECT
    table_name,
    column_name,
    data_type,
    is_nullable,
    definition,
    workflow_notes,
    qa_qc_notes
FROM grp.data_dictionary
WHERE table_name = 'paper'
  AND column_name = 'paperid';

-- The current repository entry describes paperid as a unique,
-- non-null identifier and does not state that it is auto-generated.
-- No data dictionary change is expected unless the live entry differs.