-- =====================================================
-- Change 020 Diagnostics
-- Purpose: Diagnose identity-generation or insertion
--          issues involving grp.paper.paperid
-- =====================================================

-- -----------------------------------------------------
-- 1. Inspect the paper table structure
-- -----------------------------------------------------

SELECT
    column_name,
    data_type,
    is_nullable,
    column_default,
    is_identity,
    identity_generation,
    ordinal_position
FROM information_schema.columns
WHERE table_schema = 'grp'
  AND table_name = 'paper'
ORDER BY ordinal_position;


-- -----------------------------------------------------
-- 2. Inspect all constraints on grp.paper
-- -----------------------------------------------------

SELECT
    con.conname AS constraint_name,
    con.contype AS constraint_type,
    con.convalidated AS is_validated,
    pg_get_constraintdef(con.oid) AS constraint_definition
FROM pg_constraint con
WHERE con.conrelid = 'grp.paper'::regclass
ORDER BY con.contype, con.conname;


-- -----------------------------------------------------
-- 3. Inspect PostgreSQL's internal identity flag
-- -----------------------------------------------------

SELECT
    att.attname AS column_name,
    att.attnotnull AS is_not_null,
    att.attidentity AS identity_code,
    CASE att.attidentity
        WHEN 'a' THEN 'GENERATED ALWAYS'
        WHEN 'd' THEN 'GENERATED BY DEFAULT'
        ELSE 'NOT IDENTITY'
    END AS identity_definition
FROM pg_attribute att
WHERE att.attrelid = 'grp.paper'::regclass
  AND att.attname = 'paperid'
  AND NOT att.attisdropped;


-- -----------------------------------------------------
-- 4. Locate any sequence associated with paperid
-- -----------------------------------------------------

SELECT
    pg_get_serial_sequence(
        'grp.paper',
        'paperid'
    ) AS associated_sequence;


-- -----------------------------------------------------
-- 5. Inspect sequence dependencies on grp.paper
-- -----------------------------------------------------

SELECT
    seq_ns.nspname AS sequence_schema,
    seq.relname AS sequence_name,
    dep.deptype AS dependency_type,
    tbl_ns.nspname AS table_schema,
    tbl.relname AS table_name,
    att.attname AS column_name
FROM pg_class seq
JOIN pg_namespace seq_ns
  ON seq_ns.oid = seq.relnamespace
JOIN pg_depend dep
  ON dep.objid = seq.oid
JOIN pg_class tbl
  ON tbl.oid = dep.refobjid
JOIN pg_namespace tbl_ns
  ON tbl_ns.oid = tbl.relnamespace
LEFT JOIN pg_attribute att
  ON att.attrelid = tbl.oid
 AND att.attnum = dep.refobjsubid
WHERE seq.relkind = 'S'
  AND tbl_ns.nspname = 'grp'
  AND tbl.relname = 'paper'
ORDER BY seq_ns.nspname, seq.relname;


-- -----------------------------------------------------
-- 6. Summarize existing paper identifiers
-- -----------------------------------------------------

SELECT
    COUNT(*) AS paper_count,
    COUNT(paperid) AS populated_paperids,
    COUNT(DISTINCT paperid) AS distinct_paperids,
    MIN(paperid) AS minimum_paperid,
    MAX(paperid) AS maximum_paperid
FROM grp.paper;


-- -----------------------------------------------------
-- 7. Identify duplicate identifiers, if any
-- -----------------------------------------------------

SELECT
    paperid,
    COUNT(*) AS occurrence_count
FROM grp.paper
GROUP BY paperid
HAVING COUNT(*) > 1
ORDER BY paperid;

-- Expected: zero rows. The primary key should prevent duplicates.


-- -----------------------------------------------------
-- 8. Inspect foreign keys referencing grp.paper
-- -----------------------------------------------------

SELECT
    con.conrelid::regclass AS referencing_table,
    con.conname AS constraint_name,
    con.convalidated AS is_validated,
    pg_get_constraintdef(con.oid) AS constraint_definition
FROM pg_constraint con
WHERE con.contype = 'f'
  AND con.confrelid = 'grp.paper'::regclass
ORDER BY con.conrelid::regclass::text, con.conname;


-- -----------------------------------------------------
-- 9. Inspect views that depend directly or indirectly
--    on grp.paper
-- -----------------------------------------------------

SELECT DISTINCT
    view_ns.nspname AS view_schema,
    view.relname AS view_name
FROM pg_depend dep
JOIN pg_rewrite rewrite
  ON rewrite.oid = dep.objid
JOIN pg_class view
  ON view.oid = rewrite.ev_class
JOIN pg_namespace view_ns
  ON view_ns.oid = view.relnamespace
WHERE dep.refobjid = 'grp.paper'::regclass
  AND view.relkind = 'v'
ORDER BY view_schema, view_name;

-- Dropping an identity property does not change the column name or
-- type, so dependent views are not expected to require updates.