-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 4: Add project object crosswalks
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.project_object_crosswalk (
    project_object_crosswalkid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    database text NOT NULL,

    projectid integer NOT NULL,

    import_projectid integer
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    object_type text NOT NULL,

    contributor_object_code text NOT NULL,
    contributor_object_label text,
    contributor_object_description text,

    grp_object_type text NOT NULL,
    grp_object_id integer,
    grp_object_code text,

    valid_from date,
    valid_to date,
    is_current boolean DEFAULT true,

    created_at timestamp without time zone DEFAULT now(),
    notes text,

    CONSTRAINT project_object_crosswalk_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT project_object_crosswalk_object_type_check
        CHECK (object_type IN (
            'project',
            'site',
            'area',
            'plot',
            'subplot',
            'treatment',
            'species',
            'sample',
            'observation',
            'other'
        )),

    CONSTRAINT project_object_crosswalk_current_date_check
        CHECK (
            valid_to IS NULL
            OR valid_from IS NULL
            OR valid_to >= valid_from
        )
);

COMMENT ON TABLE grp.project_object_crosswalk IS
'Stores reusable contributor-to-GRP object mappings for future imports, such as contributor plot codes mapped to GRP area or plot identifiers.';

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_project
ON grp.project_object_crosswalk(database, projectid);

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_import_projectid
ON grp.project_object_crosswalk(import_projectid);

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_lookup
ON grp.project_object_crosswalk(database, projectid, object_type, contributor_object_code);

CREATE INDEX IF NOT EXISTS idx_project_object_crosswalk_current
ON grp.project_object_crosswalk(database, projectid, object_type, is_current);