-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 5: Add import validation issue tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_validation_issue (
    import_validation_issueid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_projectid integer
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    import_artifactid integer
        REFERENCES grp.import_artifact(import_artifactid)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    source_file text,
    source_sheet text,
    source_row_number integer,
    source_column text,

    target_table text,
    target_column text,

    issue_type text NOT NULL,
    issue_severity text NOT NULL DEFAULT 'warning',

    raw_value text,
    suggested_resolution text,

    resolved boolean DEFAULT false,
    resolved_at timestamp without time zone,
    resolution_notes text,

    notes text,

    CONSTRAINT import_validation_issue_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_validation_issue_severity_check
        CHECK (issue_severity IN (
            'info',
            'warning',
            'error',
            'blocker'
        )),

    CONSTRAINT import_validation_issue_type_check
        CHECK (issue_type IN (
            'missing_required_value',
            'lookup_mismatch',
            'species_code_not_found',
            'duplicate_key',
            'date_parse_error',
            'schema_gap',
            'unmapped_object',
            'unexpected_value',
            'data_type_mismatch',
            'referential_integrity_issue',
            'other'
        ))
);

COMMENT ON TABLE grp.import_validation_issue IS
'Tracks import warnings, errors, blockers, schema gaps, unmapped objects, and other issues discovered during staging, validation, or import.';

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_import_batchid
ON grp.import_validation_issue(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_import_projectid
ON grp.import_validation_issue(import_projectid);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_project
ON grp.import_validation_issue(database, projectid);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_severity
ON grp.import_validation_issue(issue_severity);

CREATE INDEX IF NOT EXISTS idx_import_validation_issue_resolved
ON grp.import_validation_issue(resolved);


-- =====================================================
-- Remove replaced import object mapping table
-- =====================================================

DROP TABLE IF EXISTS grp.import_object_map;