-- =====================================================
-- Species Table Refinement
-- Change 018: Species table refinement
-- Date: 2026-06-05
-- Purpose: Make ID auto-generated and refine lifespan type reference
-- =====================================================

-- Redefine grp.species.speciesid as auto-generated

ALTER TABLE grp.species
ALTER COLUMN speciesid
ADD GENERATED BY DEFAULT AS IDENTITY;

-- Rename grp.species_lifespan.description to type

ALTER TABLE grp.species_lifespan
RENAME COLUMN description TO type;

ALTER TABLE grp.species_lifespan
DROP CONSTRAINT "FK_Species_Lifespan.Description";

-- Rename grp.species_lifespan constraint accordingly

ALTER TABLE grp.species_lifespan
ADD CONSTRAINT "FK_Species_Lifespan.Type"
FOREIGN KEY (type)
REFERENCES grp.lifespan(type);

-- =====================================================
-- Data Dictionary Update
-- Related Change ID: Change 018
-- Description: Refine species tables
-- =====================================================

-- 1. Update species.speciesid to reflect auto-generated identity */

UPDATE grp.data_dictionary
SET
    definition = 'Auto-generated primary key for each species or taxon record.',
    workflow_notes = 'Generated by PostgreSQL as an identity column. Do not manually populate during imports.',
    qa_qc_notes = 'Used as the primary key for species records and as the foreign key target for species-related join tables.'
WHERE table_name = 'species'
  AND column_name = 'speciesid';

-- 2. Rename data_dictionary entry from species_lifespan.description to species_lifespan.type */

UPDATE grp.data_dictionary
SET
    column_name = 'type',
    definition = 'Lifespan category assigned to a species.',
    workflow_notes = 'Must match an existing value in grp.lifespan.type.',
    allowed_values = 'annual; biennial; perennial',
    example = 'perennial',
    qa_qc_notes = 'Foreign key constrained to grp.lifespan(type). A species may have more than one lifespan type through this join table.'
WHERE table_name = 'species_lifespan'
  AND column_name = 'description';

-- ============================================================
-- Rebuild full_species view
-- ============================================================

DROP VIEW IF EXISTS grp.full_species;

CREATE VIEW grp.full_species AS
SELECT
    s.speciesid,
    s.species_code,
    s."group",
    s."order",
    s.family,
    s.genus,
    s.species,
    s.subtype,
    s.subtype_name,
STRING_AGG(sl.type, '; ' ORDER BY sl.type) AS lifespan,
    s.lifeform
FROM grp.species s
LEFT JOIN grp.species_lifespan sl
    ON s.speciesid = sl.speciesid
GROUP BY
    s.speciesid,
    s.species_code,
    s."group",
    s."order",
    s.family,
    s.genus,
    s.species,
    s.subtype,
    s.subtype_name,
    s.lifeform
ORDER BY s.speciesid;