-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 3: Add transformation tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_transformation_step (
    import_transformation_stepid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_projectid integer NOT NULL
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    step_order integer NOT NULL,

    step_name text NOT NULL,

    step_description text,

    transformation_type text,

    software_or_language text,

    notes text,

    CONSTRAINT import_transformation_step_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_transformation_step_order_check
        CHECK (step_order > 0)
);

COMMENT ON TABLE grp.import_transformation_step IS
'Documents ordered transformation steps showing how raw or contributed data become harmonized/import-ready data.';

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_import_projectid
ON grp.import_transformation_step(import_projectid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_import_batchid
ON grp.import_transformation_step(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_project
ON grp.import_transformation_step(database, projectid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_order
ON grp.import_transformation_step(import_projectid, step_order);


CREATE TABLE IF NOT EXISTS grp.import_transformation_step_artifact (
    import_transformation_step_artifactid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_transformation_stepid integer NOT NULL
        REFERENCES grp.import_transformation_step(import_transformation_stepid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_artifactid integer NOT NULL
        REFERENCES grp.import_artifact(import_artifactid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    artifact_role text NOT NULL,

    notes text,

    CONSTRAINT import_transformation_step_artifact_role_check
        CHECK (artifact_role IN (
            'input',
            'output',
            'code',
            'lookup',
            'mapping',
            'documentation',
            'other'
        ))
);

COMMENT ON TABLE grp.import_transformation_step_artifact IS
'Links artifacts to transformation steps as inputs, outputs, code, mappings, lookups, or documentation.';

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_artifact_stepid
ON grp.import_transformation_step_artifact(import_transformation_stepid);

CREATE INDEX IF NOT EXISTS idx_import_transformation_step_artifact_artifactid
ON grp.import_transformation_step_artifact(import_artifactid);