-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 1: Separate import batches from import projects
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_project (
    import_projectid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer
        REFERENCES grp.project(projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    source_folder text,

    contribution_type text,

    contribution_period text,

    documentation_tier text,

    import_status text DEFAULT 'planned',

    import_started_at timestamp without time zone,

    import_completed_at timestamp without time zone,

    supersedes_import_projectid integer
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    is_current_version boolean DEFAULT true,

    notes text,

    CONSTRAINT import_project_contribution_type_check
        CHECK (contribution_type IN (
            'initial_import',
            'additional_contribution',
            'correction',
            'reprocessing',
            'test_import'
        )),

    CONSTRAINT import_project_documentation_tier_check
        CHECK (
            documentation_tier IS NULL
            OR documentation_tier IN (
                'legacy_minimal',
                'legacy_documented',
                'transformation_documented',
                'fully_reproducible'
            )
        ),

    CONSTRAINT import_project_status_check
        CHECK (import_status IN (
            'planned',
            'staged',
            'validated',
            'imported',
            'failed',
            'skipped'
        ))
);

COMMENT ON TABLE grp.import_project IS
'Tracks one project contribution/import event within an import batch. Allows repeated future contributions for the same project.';

CREATE INDEX IF NOT EXISTS idx_import_project_import_batchid
ON grp.import_project(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_project_projectid
ON grp.import_project(projectid);