-- =====================================================
-- Change 017 — Import Tracking and Provenance Framework
-- Stage 2: Add artifact tracking
-- =====================================================

CREATE TABLE IF NOT EXISTS grp.import_artifact (
    import_artifactid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    import_projectid integer NOT NULL
        REFERENCES grp.import_project(import_projectid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    import_batchid integer NOT NULL
        REFERENCES grp.import_batch(import_batchid)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    database text NOT NULL,

    projectid integer,

    artifact_type text NOT NULL,

    artifact_subtype text,

    file_name text,

    file_extension text,

    file_path_or_storage_key text,

    storage_bucket text,

    file_hash text,

    source_layer text,

    workflow_stage text,

    created_by text,

    created_date date,

    loaded_at timestamp without time zone,

    notes text,

    CONSTRAINT import_artifact_project_fk
        FOREIGN KEY (database, projectid)
        REFERENCES grp.project(database, projectid)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT import_artifact_type_check
        CHECK (artifact_type IN (
            'raw_data',
            'harmonized_data',
            'transformation_code',
            'mapping_table',
            'transformation_table',
            'processed_output',
            'metadata',
            'notes',
            'other'
        ))
);

COMMENT ON TABLE grp.import_artifact IS
'Catalogues files and other provenance artifacts associated with project imports, including raw data, harmonized data, code, mapping tables, transformation tables, outputs, metadata, and documentation.';

CREATE INDEX IF NOT EXISTS idx_import_artifact_import_projectid
ON grp.import_artifact(import_projectid);

CREATE INDEX IF NOT EXISTS idx_import_artifact_import_batchid
ON grp.import_artifact(import_batchid);

CREATE INDEX IF NOT EXISTS idx_import_artifact_project
ON grp.import_artifact(database, projectid);

CREATE INDEX IF NOT EXISTS idx_import_artifact_type
ON grp.import_artifact(artifact_type);