-- =====================================================
-- Import Tests
-- Related Change ID: Change 018
-- Description: Populate species tables
-- =====================================================

-- ============================================================
-- Verify table schema changes
-- ============================================================

-- Verify ID auto-generation for grp.species.speciesid

SELECT
    column_name,
    is_identity,
    identity_generation
FROM information_schema.columns
WHERE table_schema = 'grp'
  AND table_name = 'species'
  AND column_name = 'speciesid';

-- Confirm renamed column

SELECT
    column_name
FROM information_schema.columns
WHERE table_schema = 'grp'
  AND table_name = 'species_lifespan'
ORDER BY ordinal_position;

-- Confirm FK references lifespan lookup

SELECT
    tc.table_name,
    kcu.column_name,
    ccu.table_name AS referenced_table,
    ccu.column_name AS referenced_column
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu
    ON tc.constraint_name = kcu.constraint_name
   AND tc.table_schema = kcu.table_schema
JOIN information_schema.constraint_column_usage ccu
    ON tc.constraint_name = ccu.constraint_name
   AND tc.table_schema = ccu.table_schema
WHERE tc.constraint_type = 'FOREIGN KEY'
  AND tc.table_schema = 'grp'
  AND tc.table_name = 'species_lifespan';

-- Confirm view runs and has expected row count

SELECT
    (SELECT COUNT(*) FROM grp.species) AS species_count,
    (SELECT COUNT(*) FROM grp.full_species) AS full_species_count,
    CASE
        WHEN (SELECT COUNT(*) FROM grp.species)
           = (SELECT COUNT(*) FROM grp.full_species)
        THEN 'PASS'
        ELSE 'FAIL'
    END AS result;

-- Confirm full_species uses lifespan values from species_lifespan.type

SELECT
    viewname,
    definition
FROM pg_views
WHERE schemaname = 'grp'
  AND viewname = 'full_species';

-- Confirm species.speciesid dictionary entry reflects identity/autogenerated role

SELECT
    table_name,
    column_name,
    definition,
    workflow_notes,
    qa_qc_notes
FROM grp.data_dictionary
WHERE table_name = 'species'
  AND column_name = 'speciesid';

-- Confirm species_lifespan.type replaced description correctly

SELECT
    table_name,
    column_name,
    definition,
    workflow_notes,
    allowed_values,
    example,
    qa_qc_notes
FROM grp.data_dictionary
WHERE table_name = 'species_lifespan'
  AND column_name IN ('type', 'description')
ORDER BY column_name;

-- Confirm lifeform lookup table exists and has expected values

SELECT *
FROM grp.lifeform
ORDER BY type;

-- Confirm lifeform_check was removed from grp.species

SELECT
    conname AS constraint_name,
    contype AS constraint_type,
    pg_get_constraintdef(oid) AS constraint_definition
FROM pg_constraint
WHERE conrelid = 'grp.species'::regclass
  AND conname = 'lifeform_check';

-- Confirm species.lifeform now has FK to grp.lifeform(type) */

SELECT
    conname AS constraint_name,
    contype AS constraint_type,
    pg_get_constraintdef(oid) AS constraint_definition
FROM pg_constraint
WHERE conrelid = 'grp.species'::regclass
  AND conname = 'FK_Species.Lifeform';

-- Confirm current species rows, if any, all pass the lookup

SELECT
    s.lifeform
FROM grp.species s
LEFT JOIN grp.lifeform lf
  ON s.lifeform = lf.type
WHERE s.lifeform IS NOT NULL
  AND lf.type IS NULL;

-- Check new data_dictionary for lifeform lookup table

SELECT
    table_name,
    column_name,
    data_type,
    is_nullable,
    definition,
    workflow_notes,
    allowed_values,
    example,
    qa_qc_notes,
    display_order
FROM grp.data_dictionary
WHERE table_name IN ('lifeform', 'species')
  AND (
      table_name = 'lifeform'
      OR column_name = 'lifeform'
  )
ORDER BY table_name, display_order;